### ISSUE TITLE
why not work ofv(open view mode)  in  word

### ISSUE THREAD

**Issue by mhmdda** [ramondeklein/nwebdav#41] opened 2018-10-07 08:32 UTC
i use under link
ms-word:ofv|u|https://xxxxxxx/webdav/y.doc
but open document Edit mode. I want Open Document On View Mode and user Fails Edit Document .
desktop word version is 2016

**Comment by ramondeklein** [comment] 2018-10-07 15:53
Duplicate of #40.

**Closed by ramondeklein** 2018-10-07 15:53 UTC
